use MySql
 


 --------------------- DAY 2 ASSIGNMENT ------------------------------

--1 
SELECT * FROM EMP WHERE JOB= 'MANAGER'

--2
SELECT ENAME, SAL FROM EMP WHERE SAL>1000 ORDER BY SAL DESC

--3
SELECT ENAME, SAL FROM EMP WHERE ENAME != 'JAMES'

--4 
SELECT * FROM EMP WHERE ENAME LIKE 'S%'

--5
SELECT ENAME FROM EMP WHERE ENAME LIKE '%A%'

--6
SELECT ENAME FROM EMP WHERE ENAME LIKE '__L%'

--7
SELECT ENAME, (SAL/30) AS 'DAILY SALARY' FROM EMP WHERE ENAME = 'JONES'

--8
SELECT SUM(SAL) AS 'TOTAL MONTHLY SALARY' FROM EMP

--9 NOT SURE
SELECT EMPNO, ENAME, AVG(SAL*12) AS 'AVERAGE ANNUAL SALARY', AVG(SAL) AS 'AVERAGE SALARY' FROM EMP GROUP BY EMPNO, ENAME 

--10
SELECT ENAME, JOB, SAL, DEPTNO FROM EMP WHERE JOB != 'SALESMAN'

--11
SELECT DISTINCT(e.DEPTNO), d.DNAME FROM EMP e JOIN DEPT d ON e.DEPTNO = d.DEPTNO

--12
 SELECT ENAME AS 'EMPLOYEE', SAL AS 'MONTHLY SALARY', DEPTNO FROM EMP WHERE SAL > 1500 AND DEPTNO IN (10,30)

 --13
 SELECT ENAME, JOB, SAL FROM EMP WHERE JOB IN ('MANAGER', 'ANALYST') AND SAL NOT IN (1000,3000,5000)

 --14
 SELECT ENAME, SAL, COMM FROM EMP WHERE COMM > (SAL+(SAL*10/100))

 --15
 SELECT * FROM EMP WHERE ENAME LIKE '%L%L%' AND DEPTNO=30 OR MGR_ID=7782

 --16
SELECT ENAME, DATEDIFF(YEAR,DATENAME(YEAR,HIRE_DATE),DATENAME(YEAR,GETDATE())) AS EXPERIENCE
FROM EMP 
WHERE DATEDIFF(YEAR,DATENAME(YEAR,HIRE_DATE),DATENAME(YEAR,GETDATE()))  >10 AND DATEDIFF(YEAR,DATENAME(YEAR,HIRE_DATE),DATENAME(YEAR,GETDATE())) < 20 


 --17
 SELECT d.DEPTNO, d.DNAME, e.ENAME FROM DEPT d, EMP e WHERE d.DEPTNO = e.DEPTNO ORDER BY d.DNAME ASC, e.ENAME DESC

 --18
SELECT ENAME, DATEDIFF(YEAR, HIRE_DATE, GETDATE()) AS 'EXPERIENCE YEARS' FROM EMP WHERE ENAME='MILLER'

